# http://module-build.sourceforge.net/META-spec-current.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MIDI-SoundFont
version:      1.02
version_from: SoundFont.pm
installdirs:  site
license:      perl
distribution_type: module
requires:
  perl: ">= 5.006001"
  File::Format::RIFF:
  Archive::Zip:
  File::Tmp:
  File::Basename:
  LWP::Simple:
  Strings::Approx:
  MIDI:
build_requires:
  Test::Simple: 0
  Data::Dumper:
generated_by: /usr/bin/vim
